### import all Librarys

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

PART - A

What is Data Analysis?


->Data Analysis is the process of collecting, cleaning, transforming, and interpreting data to discover useful information, identify patterns, and support decision-making.

The main goal of data analysis is to convert raw data into meaningful insights.

Steps of Data Analysis
Data Collection
Data Cleaning
Data Transformation
Data Exploration
Data Visualization
Interpretation and Decision Making
Importance
Improves decision making
Identifies trends and patterns
Helps in prediction and forecasting
Supports business growth

How to Plan a Data Science Project?

-> A Data Science project should follow a structured approach.

1. Business Understanding

Define the problem and project objectives.

Example:
Predict whether a customer will default on a loan.

2. Data Collection

Gather data from different sources such as:

CSV files
Databases
APIs
JSON files

3. Data Understanding

Analyze:

Data types
Missing values
Outliers
Data distribution

4. Data Preprocessing
Handle missing values
Remove outliers
Encode categorical variables
Scale features

5. Feature Engineering

Create useful features from existing data.

6. Model Building

Train machine learning models.

7. Evaluation

Measure model performance using metrics.

8. Deployment

Deploy the model for real-world use.

How to Frame a Machine Learning Problem?

-> Framing a Machine Learning problem means converting a business problem into a machine learning task.

Step 1: Define Objective

Example:

Predict loan default.

Step 2: Identify Target Variable

Target:

default_flag

0 = No Default

1 = Default

Step 3: Identify Features

Input Variables:

age

gender

annual_income

loan_amount

credit_score

repayment_history

transaction_count

spending_ratio

Step 4: Select ML Type

Since target has:

0 or 1

It is a:

Binary Classification Problem

Step 5: Define Evaluation Metric
Accuracy

Precision

Recall

F1 Score

Explain Tensors with NumPy Examples
Definition

-> A Tensor is a mathematical structure used to represent data in multiple dimensions.

A tensor can be:

Tensor Type	Example

Scalar	Single Number

Vector	1D Array

Matrix	2D Array

Higher Order Tensor	3D+ Array

0-D Tensor (Scalar)

import numpy as np

scalar = np.array(10)

print(scalar)

print(scalar.ndim)

Output:

10

0
1-D Tensor (Vector)

vector = np.array([10,20,30,40])

print(vector)

print(vector.ndim)

Output:

[10 20 30 40]

1

2-D Tensor (Matrix)

matrix = np.array([

    [1,2,3],
    [4,5,6]
])

print(matrix)

print(matrix.ndim)

Output:

[[1 2 3]

 [4 5 6]]

2

3-D Tensor

tensor3d = np.array([

    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(tensor3d.ndim)

Output:

3
Why Tensors are Important?

Used in Deep Learning

Store multi-dimensional data

Efficient mathematical operations

Used by TensorFlow and PyTorch

PART = B

In [ ]:
import sqlite3

df1 = pd.read_csv('/content/credit_risk_500(2).csv')
df2 = pd.read_json('/content/customer_metadata(2).json')
conn = sqlite3.connect('/content/loan_history(2).db')
df3 = pd.read_sql('SELECT * FROM loan_history', conn)
conn.close()

In [ ]:
df1.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,CUST001,NaN,Male,West,Secondary,NaN,NaN,6.211870e+05,Education,616.0,10,395,0.289,2019-08-27,1
1,CUST002,69.0,Male,East,Primary,Self-Employed,1259639.0,4.961687e+05,Business,803.0,12,168,0.158,2021-03-07,1
2,CUST003,NaN,NaN,North,Graduate,NaN,NaN,1.444485e+06,Other,NaN,5,66,0.260,2021-12-16,1
3,CUST004,32.0,Male,East,Primary,Salaried,1889080.0,7.213754e+05,Other,708.0,12,87,1.044,2020-12-16,1
4,CUST005,60.0,Male,North,Secondary,Salaried,595377.0,2.765431e+06,Home,980.0,4,203,0.857,2022-05-05,1

In [ ]:
df2.head()

  customer_id marital_status  dependents
0     CUST001         Single           3
1     CUST002         Single           4
2     CUST003         Single           3
3     CUST004         Single           3
4     CUST005         Single           1

In [ ]:
df3.head()

  customer_id  loan_tenure  interest_rate  previous_loans
0     CUST001           51          16.59               5
1     CUST002            8           8.08               0
2     CUST003           23          11.80               4
3     CUST004           29          17.59               1
4     CUST005           52          16.18               4

### api_data = {

In [ ]:
api_data = {
    "inflation_rate":5.4,
    "repo_rate":6.5,
    "gdp_growth":7.1
}

api_df = pd.DataFrame([api_data])

api_df

   inflation_rate  repo_rate  gdp_growth
0             5.4        6.5         7.1

### merged_df = df1.merge(

In [ ]:
merged_df = df1.merge(
    df2,
    on="customer_id",
    how="left"
)

merged_df = merged_df.merge(
    df3,
    on="customer_id",
    how="left"
)

merged_df.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag,marital_status,dependents,loan_tenure,interest_rate,previous_loans
0,CUST001,NaN,Male,West,Secondary,NaN,NaN,6.211870e+05,Education,616.0,10,395,0.289,2019-08-27,1,Single,3,51,16.59,5
1,CUST002,69.0,Male,East,Primary,Self-Employed,1259639.0,4.961687e+05,Business,803.0,12,168,0.158,2021-03-07,1,Single,4,8,8.08,0
2,CUST003,NaN,NaN,North,Graduate,NaN,NaN,1.444485e+06,Other,NaN,5,66,0.260,2021-12-16,1,Single,3,23,11.80,4
3,CUST004,32.0,Male,East,Primary,Salaried,1889080.0,7.213754e+05,Other,708.0,12,87,1.044,2020-12-16,1,Single,3,29,17.59,1
4,CUST005,60.0,Male,North,Secondary,Salaried,595377.0,2.765431e+06,Home,980.0,4,203,0.857,2022-05-05,1,Single,1,52,16.18,4

PART - C

In [ ]:
merged_df.shape

(500, 20)

### merged_df.columns

In [ ]:
merged_df.columns

Index(['customer_id', 'age', 'gender', 'region', 'education_level',
       'employment_type', 'annual_income', 'loan_amount', 'loan_purpose',
       'credit_score', 'repayment_history', 'transaction_count',
       'spending_ratio', 'join_date', 'default_flag', 'marital_status',
       'dependents', 'loan_tenure', 'interest_rate', 'previous_loans'],
      dtype='object')

### merged_df.info()

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        500 non-null    object
 1   age                450 non-null    float64
 2   gender             460 non-null    object
 3   region             500 non-null    object
 4   education_level    500 non-null    object
 5   employment_type    450 non-null    object
 6   annual_income      451 non-null    float64
 7   loan_amount        500 non-null    float64
 8   loan_purpose       500 non-null    object
 9   credit_score       460 non-null    float64
 10  repayment_history  500 non-null    int64
 11  transaction_count  500 non-null    int64
 12  spending_ratio     500 non-null    float64
 13  join_date          500 non-null    object
 14  default_flag       500 non-null    int64
 15  marital_status     500 non-null    object
 16  dependents         500 non-null    int64
 17  loan_tenure        500 non-null    int64
 18  interest_rate      500 non-null    float64
 19  previous_loans     500 non-null    int64
dtypes: float64(6), int64(6), object(8)
memory usage: 78.3+ KB

### merged_df.describe()

In [ ]:
merged_df.describe()

,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio,default_flag,dependents,loan_tenure,interest_rate,previous_loans
count,450.000000,4.510000e+02,5.000000e+02,460.000000,500.000000,500.000000,500.00000,500.00000,500.000000,500.000000,500.00000,500.000000
mean,44.248889,1.458878e+06,6.347917e+05,579.591304,6.260000,256.504000,0.40923,0.87000,2.012000,32.086000,12.51286,2.526000
std,15.328774,1.582419e+06,8.169926e+05,158.471162,3.781137,142.135608,0.23208,0.33664,1.433865,16.035363,3.19504,1.761684
min,18.000000,1.696750e+05,2.752517e+04,100.000000,0.000000,10.000000,0.01200,0.00000,0.000000,6.000000,7.01000,0.000000
25%,32.000000,7.746085e+05,2.448296e+05,450.500000,3.000000,132.000000,0.21900,1.00000,1.000000,18.000000,10.04500,1.000000
50%,45.000000,1.374744e+06,4.231253e+05,569.500000,6.000000,254.500000,0.38200,1.00000,2.000000,31.000000,12.44000,3.000000
75%,56.000000,1.889270e+06,7.347875e+05,715.250000,10.000000,386.250000,0.56975,1.00000,3.000000,46.000000,15.35000,4.000000
max,70.000000,2.500000e+07,9.000000e+06,1000.000000,12.000000,499.000000,1.17400,1.00000,4.000000,60.000000,18.00000,5.000000

### !pip install ydata-profiling

In [ ]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 2.0 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 2.5 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 2.9 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 3.3 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 3.2 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 2.9 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

### from ydata_profiling import ProfileReport

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(
    merged_df,
    title="Credit Risk Report"
)

profile.to_file("credit_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]
 35%|███▌      | 7/20 [00:00<00:00, 66.94it/s]
100%|██████████| 20/20 [00:00<00:00, 67.65it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

### merged_df.isnull().sum()

In [ ]:
merged_df.isnull().sum()

customer_id           0
age                  50
gender               40
region                0
education_level       0
employment_type      50
annual_income        49
loan_amount           0
loan_purpose          0
credit_score         40
repayment_history     0
transaction_count     0
spending_ratio        0
join_date             0
default_flag          0
marital_status        0
dependents            0
loan_tenure           0
interest_rate         0
previous_loans        0
dtype: int64

### from sklearn.impute import SimpleImputer

In [ ]:
from sklearn.impute import SimpleImputer

mean_imp = SimpleImputer(strategy="mean")

merged_df["age"] = mean_imp.fit_transform(
    merged_df[["age"]]
)

### from pyspark.sql.merge import MergeIntoWriter

In [ ]:
from pyspark.sql.merge import MergeIntoWriter
merged_df["age"].isnull().sum()

np.int64(0)

### median_imp = SimpleImputer(

In [ ]:
median_imp = SimpleImputer(
    strategy="median"
)

merged_df["annual_income"] = (
    median_imp.fit_transform(
        merged_df[["annual_income"]]
    )
)

### merged_df["annual_income"].isnull().sum()

In [ ]:
merged_df["annual_income"].isnull().sum()

np.int64(0)

### cat_imp = SimpleImputer(

In [ ]:
cat_imp = SimpleImputer(
    strategy="most_frequent"
)

merged_df["employment_type"] = (
    cat_imp.fit_transform(
        merged_df[["employment_type"]]
    ).ravel()
)

### merged_df["employment_type"].isnull().sum()

In [ ]:
merged_df["employment_type"].isnull().sum()

np.int64(0)

### merged_df["income_missing"] = (merged_df["annual_i

In [ ]:
merged_df["income_missing"] = (merged_df["annual_income"].isnull().astype(int))

### merged_df["income_missing"].value_counts()

In [ ]:
merged_df["income_missing"].value_counts()

income_missing
0    500
Name: count, dtype: int64

### random_sample = merged_df["annual_income"].dropna(

In [ ]:
random_sample = merged_df["annual_income"].dropna()
merged_df.loc[merged_df["annual_income"].isnull(), "annual_income"] = \
    np.random.choice(random_sample, merged_df["annual_income"].isnull().sum())

### random_sample

In [ ]:
random_sample

0      0.037419
1     -0.142882
2      0.037419
3      0.849008
4     -1.174975
         ...
495    0.037419
496    1.398000
497    0.037419
498    0.559809
499   -1.444311
Name: annual_income, Length: 500, dtype: float64

### random_sample = merged_df["annual_income"].dropna(

In [ ]:
random_sample = merged_df["annual_income"].dropna()
merged_df.loc[merged_df["annual_income"].isnull(),"annual_income"] = np.random.choice(random_sample, merged_df["annual_income"].isnull().sum())

### random_sample

In [ ]:
random_sample

0      0.037419
1     -0.142882
2      0.037419
3      0.849008
4     -1.174975
         ...
495    0.037419
496    1.398000
497    0.037419
498    0.559809
499   -1.444311
Name: annual_income, Length: 500, dtype: float64

### from sklearn.impute import KNNImputer

In [ ]:
from sklearn.impute import KNNImputer

knn = KNNImputer(
    n_neighbors=5
)

cols = [
    "annual_income",
    "loan_amount",
    "credit_score"
]

merged_df[cols] = (
    knn.fit_transform(
        merged_df[cols]
    )
)

### knn

In [ ]:
knn

KNNImputer()

### from sklearn.experimental import (

In [ ]:
from sklearn.experimental import (
    enable_iterative_imputer
)

from sklearn.impute import (
    IterativeImputer
)

mice = IterativeImputer()

merged_df[cols] = (
    mice.fit_transform(
        merged_df[cols]
    )
)

### merged_df

In [ ]:
merged_df

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,loan_purpose_Other,income_group,transaction_quantile,transaction_cluster,log_spending,reciprocal_spending,sqrt_spending,debt_income_ratio,avg_monthly_transactions,spending_income_ratio
0,CUST001,44.248889,1,2,Salaried,0.037419,0.528092,0.573333,0.571429,0.791583,...,False,High,3,0,0.253867,0.775795,0.537587,14.112784,0.131931,0.010814
1,CUST002,69.000000,1,1,Self-Employed,-0.142882,0.183832,0.781111,0.857143,0.336673,...,False,Medium,1,3,0.146694,0.863558,0.397492,-1.286602,0.056112,-0.022575
2,CUST003,44.248889,3,3,Salaried,0.037419,1.547160,0.578000,-0.142857,0.132265,...,True,High,0,1,0.231112,0.793651,0.509902,41.346447,0.022044,0.009729
3,CUST004,32.000000,1,1,Salaried,0.849008,0.743800,0.675556,0.857143,0.174349,...,True,High,0,1,0.714909,0.489237,1.021763,0.876081,0.029058,0.886364
4,CUST005,60.000000,1,2,Salaried,-1.174975,2.034200,0.977778,-0.285714,0.406814,...,False,Low,1,3,0.618962,0.538503,0.925743,-1.731271,0.067802,-1.006953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,CUST496,44.248889,3,2,Salaried,0.037419,-1.191529,0.511111,0.714286,0.448898,...,False,High,1,3,0.074179,0.928505,0.277489,-31.842516,0.074816,0.002881
496,CUST497,70.000000,1,2,Salaried,1.398000,1.010965,0.484444,-0.428571,0.412826,...,False,Very High,1,3,0.205387,0.814332,0.477493,0.723151,0.068804,0.318744
497,CUST498,44.248889,3,3,Salaried,0.037419,0.708503,0.526000,0.142857,0.102204,...,False,High,0,1,0.149282,0.861326,0.401248,18.934110,0.017034,0.006025
498,CUST499,26.000000,0,3,Salaried,0.559809,-0.525375,0.831111,-0.142857,0.124248,...,False,High,0,1,0.287432,0.750188,0.577062,-0.938489,0.020708,0.186416
499,CUST500,29.000000,1,3,Unemployed,-1.444311,-1.144618,0.283333,0.571429,0.979960,...,False,Low,3,0,0.444045,0.641437,0.747663,0.792501,0.163327,-0.807370

### cca_df = merged_df.dropna()

In [ ]:
cca_df = merged_df.dropna()

### cca_df

In [ ]:
cca_df

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,transaction_count,spending_ratio,join_date,default_flag,marital_status,dependents,loan_tenure,interest_rate,previous_loans,income_missing
0,CUST001,44.248889,Male,West,Secondary,Salaried,1374744.0,6.211870e+05,Education,616.0,...,395,0.289,2019-08-27,1,Single,3,51,16.59,5,0
1,CUST002,69.000000,Male,East,Primary,Self-Employed,1259639.0,4.961687e+05,Business,803.0,...,168,0.158,2021-03-07,1,Single,4,8,8.08,0,0
3,CUST004,32.000000,Male,East,Primary,Salaried,1889080.0,7.213754e+05,Other,708.0,...,87,1.044,2020-12-16,1,Single,3,29,17.59,1,0
4,CUST005,60.000000,Male,North,Secondary,Salaried,595377.0,2.765431e+06,Home,980.0,...,203,0.857,2022-05-05,1,Single,1,52,16.18,4,0
5,CUST006,25.000000,Female,North,Post-Graduate,Salaried,1688510.0,4.819684e+05,Education,500.0,...,294,1.102,2023-10-20,1,Married,0,43,12.39,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,CUST494,43.000000,Male,South,Secondary,Salaried,1700184.0,1.095694e+06,Education,502.0,...,425,0.312,2022-09-18,1,Single,4,58,10.29,0,0
494,CUST495,54.000000,Other,North,Secondary,Self-Employed,238668.0,1.891248e+05,Car,491.0,...,462,0.740,2021-11-24,1,Married,2,38,13.16,5,0
496,CUST497,70.000000,Male,East,Secondary,Salaried,2234508.0,8.828206e+05,Home,536.0,...,206,0.228,2020-05-07,1,Married,2,53,7.91,0,0
498,CUST499,26.000000,Female,North,Graduate,Salaried,1706396.0,3.061374e+05,Business,848.0,...,62,0.333,2019-04-09,1,Single,0,11,9.04,0,0
499,CUST500,29.000000,Male,North,Graduate,Unemployed,420914.0,1.783728e+05,Car,355.0,...,489,0.559,2018-09-27,1,Single,4,49,12.63,5,0

Part D: Outlier Handling

In [ ]:
from scipy.stats import zscore

z_scores = np.abs(
    zscore(
        merged_df[
            [
                "annual_income",
                "loan_amount",
                "credit_score"
            ]
        ]
    )
)

outliers = (
    z_scores > 3
).any(axis=1)

merged_df_z = merged_df[
    ~outliers
]

### Q1 = merged_df[

In [ ]:
Q1 = merged_df[
    "annual_income"
].quantile(0.25)

Q3 = merged_df[
    "annual_income"
].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

merged_df_iqr = merged_df[
    (
        merged_df["annual_income"]
        >= lower
    )
    &
    (
        merged_df["annual_income"]
        <= upper
    )
]

### low = merged_df[

In [ ]:
low = merged_df[
    "annual_income"
].quantile(0.01)

high = merged_df[
    "annual_income"
].quantile(0.99)

merged_df["annual_income"] = (
    merged_df[
        "annual_income"
    ].clip(low,high)
)

### from scipy.stats.mstats import winsorize

In [ ]:
from scipy.stats.mstats import winsorize

merged_df[
    "annual_income"
] = winsorize(
    merged_df["annual_income"],
    limits=[0.01,0.01]
)

Part E: Feature Engineering

In [ ]:
merged_df.dtypes

customer_id           object
age                  float64
gender                object
region                object
education_level       object
employment_type       object
annual_income        float64
loan_amount          float64
loan_purpose          object
credit_score         float64
repayment_history      int64
transaction_count      int64
spending_ratio       float64
join_date             object
default_flag           int64
marital_status        object
dependents             int64
loan_tenure            int64
interest_rate        float64
previous_loans         int64
income_missing         int64
dtype: object

### merged_df["join_date"] = pd.to_datetime(

In [ ]:
merged_df["join_date"] = pd.to_datetime(
    merged_df["join_date"]
)

merged_df["year"] = (
    merged_df["join_date"]
    .dt.year
)

merged_df["month"] = (
    merged_df["join_date"]
    .dt.month
)

merged_df["day"] = (
    merged_df["join_date"]
    .dt.day
)

merged_df["weekday"] = (
    merged_df["join_date"]
    .dt.day_name()
)

### education_map = {

In [ ]:
education_map = {
"Primary":1,
"Secondary":2,
"Graduate":3,
"Post-Graduate":4
}

merged_df[
    "education_level"
] = (
    merged_df[
        "education_level"
    ].map(education_map)
)

### from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

merged_df["gender"] = (
    le.fit_transform(
        merged_df["gender"]
    )
)

### merged_df = pd.get_dummies(

In [ ]:
merged_df = pd.get_dummies(
    merged_df,
    columns=[
        "region",
        "loan_purpose"
    ]
)

### merged_df[

In [ ]:
merged_df[
    "income_group"
] = pd.cut(
    merged_df["annual_income"],
    bins=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

### merged_df[

In [ ]:
merged_df[
    "income_group"
] = pd.cut(
    merged_df["annual_income"],
    bins=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

### merged_df[

In [ ]:
merged_df[
    "transaction_quantile"
] = pd.qcut(
    merged_df[
        "transaction_count"
    ],
    q=4,
    labels=False
)

### from sklearn.cluster import KMeans

In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42
)

merged_df[
    "transaction_cluster"
] = (
    kmeans.fit_predict(
        merged_df[
            ["transaction_count"]
        ]
    )
)

Part F: Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

merged_df[
[
"annual_income",
"loan_amount"
]
] = scaler.fit_transform(
merged_df[
[
"annual_income",
"loan_amount"
]
]
)

### from sklearn.preprocessing import MinMaxScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()

merged_df[
[
"credit_score"
]
] = mm.fit_transform(
merged_df[
[
"credit_score"
]
]
)

### from sklearn.preprocessing import MaxAbsScaler

In [ ]:
from sklearn.preprocessing import MaxAbsScaler

ma = MaxAbsScaler()

merged_df[
[
"transaction_count"
]
] = ma.fit_transform(
merged_df[
[
"transaction_count"
]
]
)

### from sklearn.preprocessing import RobustScaler

In [ ]:
from sklearn.preprocessing import RobustScaler

rb = RobustScaler()

merged_df[
[
"repayment_history"
]
] = rb.fit_transform(
merged_df[
[
"repayment_history"
]
]
)

Part G: Transformations

In [ ]:
merged_df[
"log_spending"
] = np.log1p(
merged_df[
"spending_ratio"
]
)

### merged_df[

In [ ]:
merged_df[
"reciprocal_spending"
] = 1/(
merged_df[
"spending_ratio"
]+1
)

### merged_df[

In [ ]:
merged_df[
"sqrt_spending"
] = np.sqrt(
merged_df[
"spending_ratio"
]
)

### from sklearn.preprocessing import PowerTransformer

In [ ]:
from sklearn.preprocessing import PowerTransformer

bc = PowerTransformer(
    method="yeo-johnson"
)

merged_df[
    [
        "annual_income"
    ]
] = bc.fit_transform(
    merged_df[
        [
            "annual_income"
        ]
    ]
)

### yj = PowerTransformer(

In [ ]:
yj = PowerTransformer(
method="yeo-johnson"
)

merged_df[["loan_amount"]] = yj.fit_transform(
merged_df[["loan_amount"]])

### from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(["cat",OneHotEncoder(),["loan_purpose"],("num",StandardScaler(),["annual_income","loan_amount"])])

### merged_df["debt_income_ratio"] = (merged_df["loan_

In [ ]:
merged_df["debt_income_ratio"] = (merged_df["loan_amount"]/merged_df["annual_income"])

### merged_df["avg_monthly_transactions"] = (merged_df

In [ ]:
merged_df["avg_monthly_transactions"] = (merged_df["transaction_count"]/6)

### merged_df["spending_income_ratio"] = (merged_df["s

In [ ]:
merged_df["spending_income_ratio"] = (merged_df["spending_ratio"]*merged_df["annual_income"])

Part H Final Deliverable

In [ ]:
merged_df.to_csv("final_cleaned_dataset.csv",index=False)

### merged_df.head()

In [ ]:
merged_df.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,loan_purpose_Other,income_group,transaction_quantile,transaction_cluster,log_spending,reciprocal_spending,sqrt_spending,debt_income_ratio,avg_monthly_transactions,spending_income_ratio
0,CUST001,44.248889,1,2,Salaried,0.037419,0.528092,0.573333,0.571429,0.791583,...,False,High,3,0,0.253867,0.775795,0.537587,14.112784,0.131931,0.010814
1,CUST002,69.000000,1,1,Self-Employed,-0.142882,0.183832,0.781111,0.857143,0.336673,...,False,Medium,1,3,0.146694,0.863558,0.397492,-1.286602,0.056112,-0.022575
2,CUST003,44.248889,3,3,Salaried,0.037419,1.547160,0.578000,-0.142857,0.132265,...,True,High,0,1,0.231112,0.793651,0.509902,41.346447,0.022044,0.009729
3,CUST004,32.000000,1,1,Salaried,0.849008,0.743800,0.675556,0.857143,0.174349,...,True,High,0,1,0.714909,0.489237,1.021763,0.876081,0.029058,0.886364
4,CUST005,60.000000,1,2,Salaried,-1.174975,2.034200,0.977778,-0.285714,0.406814,...,False,Low,1,3,0.618962,0.538503,0.925743,-1.731271,0.067802,-1.006953

Final Report Conclusion

Missing Values

Mean and Median used for numerical variables.

Most Frequent used for categorical variables.

KNN and MICE provided better estimations.

Outliers

Z-score detected extreme values.

IQR handled skewed distributions.

Winsorization preserved data.

Encoding

Ordinal Encoding → education_level

Label Encoding → gender

One Hot Encoding → region, loan_purpose

Scaling

StandardScaler

MinMaxScaler

MaxAbsScaler

RobustScaler

Feature Engineering

Debt-to-Income Ratio

Monthly Transactions

Spending-to-Income Ratio

Final Dataset

Missing values handled

Outliers treated

Features encoded

Scaled and transformed

ML-ready dataset prepared